name: Reeve Shared Maintenance E2E

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  maintenance:
    uses: reeveops/reeve/.github/workflows/reeve.yml@96d7a92eb9ebc47803527d8e996e1c00329f0147
    with:
      mode: maintenance
      root: tf
