name: Reeve Shared Maintenance E2E

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  maintenance:
    uses: reeveops/reeve/.github/workflows/reeve.yml@9d67273f8830c6cde7d10b7dfec9287fb903bd76
    with:
      mode: maintenance
      root: tf
