name: Reeve Shared E2E

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, closed]
  merge_group:
    types: [checks_requested]
  issue_comment:
    types: [created]

permissions:
  contents: read
  checks: read
  pull-requests: write
  issues: write
  id-token: write

jobs:
  reeve:
    uses: reeveops/reeve/.github/workflows/reeve.yml@0fc118139931fde27444ddc3d8527b16fbc381d5
    with:
      mode: gitops
      root: tf
      opentofu_version: "1.12.6"
