name: Reeve Shared E2E

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, closed]
  issue_comment:
    types: [created]

permissions:
  contents: read
  checks: read
  pull-requests: write
  issues: write
  id-token: write

jobs:
  reeve:
    uses: reeveops/reeve/.github/workflows/reeve.yml@13b065f2c862745869cc657d9e872de049eece7d
    with:
      mode: gitops
      root: tf
      opentofu_version: "1.12.6"
