name: Reeve Shared Maintenance E2E

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  maintenance:
    uses: reeveops/reeve/.github/workflows/reeve.yml@5ef3fa3910a38775905e7048d38fbb86498c6c82
    with:
      mode: maintenance
      root: tf
